name: 'Update Facade Docblocks'

on:
  push:
    branches:
      - '*.x'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  facades:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    name: 'Update Facade Docblocks'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer config repositories.facade-documenter vcs git@github.com:laravel/facade-documenter.git
          composer require --dev laravel/facade-documenter:dev-main --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Update docblocks
        run: php -f vendor/bin/facade.php BabDev\\Breadcrumbs\\Facades\\Breadcrumbs

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update facade docblocks
          file_pattern: src/
